version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - API_URL=localhost
      - API_PORT=5000
      - API_PROTOCOL_REST=http
      - API_PROTOCOL_WS=ws
      - PORT=3000
      - IS_DOCKER=true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - URL=localhost
      - PORT=5000
    restart: always
