version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - URL=localhost
      - PORT=5000
    restart: always
